doctrine_migrations:
    dir_name: "%kernel.root_dir%/../vendor/rybakdigital/user-bundle/DoctrineMigrations"
    namespace: "RybakDigital\UserBundle\Migrations"
    table_name: "migration_versions_rd_ub"
    name: "RybakDigital User Bundle Migrations"
