services:
#    rybak_digital_user.example:
#        class: RybakDigital\Bundle\UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
services:
    rybakdigital.user.listener.guid_generator:
        class: RybakDigital\Bundle\UserBundle\Listener\GuidGenerator
        tags:
            - { name: doctrine.event_listener, event: prePersist }
