language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 7.0
      env: SYMFONY_VERSION='3.1.*'

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "5.6" && "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

install: composer update $COMPOSER_FLAGS --prefer-dist

cache:
  directories:
    - $HOME/.composer/cache/files

script:
  - phpunit --configuration travis.phpunit.xml .
